### ISSUE TITLE
Automatic service windows

### ISSUE THREAD

**Issue by danielnord2** [kristoferB/SP#32]

**Comment by kristoferB** [comment]
Each service will define what it needs as input. We need to define a format for that. This should also work for distributed services not impl in scala.

**Comment by kristoferB** [comment]
Probably the following format:
{
  // This structure can be placed anywhere in a json structure, but usually it some key-values in the root
  "key": {
     "isa": String, // What type to get the correct input method in the form
     "domain": [items], // if the input is a dropdown. Empty if not a dropdown.
     "default": Option[item]  // Both key and value may be omitted
  }
}

**Comment by kristoferB** [comment]
The new services are in place in backend in commit: fe4e926b 
Frontend to be fixed.
