### ISSUE TITLE
Fix log4j warnings that appear when using Supremica 

### ISSUE THREAD

**Issue by patrikm** [kristoferB/SP#35]
In other projects I handle the warnings by adding a "log4j.properties" file to the classpath. I don't get that to work here...

log4j.properties:
### direct log messages to stdout ###
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.SimpleLayout
log4j.rootLogger=debug, stdout

**Comment by kristoferB** [comment]
Fixed in commit b75ffa01d6829eade52bdd3a04c13a23ffd9a8fd

try it
