### ISSUE TITLE
migrating to scalajs-react 1.0.0

### ISSUE THREAD

**Issue by edvardlindelof** [kristoferB/SP#73]

**Comment by edvardlindelof** [comment]
Ran the update script and solved all compile errors except one. Diode is incompatible. Could wait until diode's 1.0.0-branch is merged in or pull it directly (https://github.com/suzaku-io/diode/pull/45)

**Comment by kristoferB** [comment]
Good work. We should wait to merge with master until react 1.0.0 final (and the diode-fix).
